# Generated by Django 4.1.2 on 2022-11-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('netid', models.CharField(max_length=80)),
                ('mealnum', models.IntegerField()),
            ],
        ),
    ]
