# Generated by Django 4.1.2 on 2022-11-20 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestmeal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donee',
        ),
    ]
