# Generated by Django 4.1.2 on 2022-11-22 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestmeal', '0007_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MS', models.IntegerField()),
                ('DD', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='DDallotment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='MSallotment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
