# Generated by Django 4.1.2 on 2022-11-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmeal', '0008_requestamount_alter_student_ddallotment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DDallotment',
            field=models.FloatField(default=0),
        ),
    ]
