# Generated by Django 4.1.2 on 2022-12-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestmeal', '0009_alter_student_ddallotment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonateAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MS', models.IntegerField()),
                ('DD', models.FloatField()),
                ('netid', models.CharField(max_length=50)),
            ],
        ),
    ]
